language: python
python:
  - "3.6"
  - "3.6-dev"

install:
  - pip install coveralls
  - pip install pipenv
  - pipenv install --dev
  - make download_data
  - pipenv run python -m csadatavis

script:
  - make typecheck
  - nosetests --with-coverage --cover-package=csadatavis

after_success:
  - coveralls
